"""A staircase is a cell labelled `E`, the same cell on every storey it climbs
— the owner's two rulings, pinned.

THE SECOND RULING (2026-10-08, DESIGN.md §39.125) changed how the scorer KNOWS a
cell is a stair, and left the first one's substance alone:

    "Mixing circulation with stairs makes sense for small buildings like
    programme house because the stairs are the entirety of the circulation. But
    for bigger buildings we will have these corridors that exist in the same
    place on each level, I think we need a new cell usage, maybe e (escalier)."

Until then a stair was INFERRED from a `C` cell stacked on every storey, which
read a corridor repeated floor over floor as a staircase and could not see a
stair that stopped below the top. Now: `E` is circulation that holds a stair; a
stacked `C` is a corridor; a shaft starts at the ground and may stop below the
top; and a shaft joins the circulation of the storeys it serves. Everything
below about the SAME CELL on each storey is the first ruling and still holds.


`graph.stack_corners_in_use` walks `dom._above_node` (Urb's `Above`, the EXACT id
path), so a storey that MERGES the cell over the stair breaks the stack and the
building has no staircase. `homemaker-py-m4d` asked whether that is a defect,
since every other vertical predicate in `dom` walks the forgiving `_above_more`,
and since 31 of the corpus's 170 ground-floor circulation stacks are in exactly
that state against 29 the scorer accepts (DESIGN.md §39.72).

THE OWNER'S RULING (2026-09-27, DESIGN.md §39.72), which is why this test exists:

    "A first floor circulation cell that is split below into circulation and some
    other usage could in principle form a staircase, and this is a common pattern
    in real buildings, eg. a mid-landing in a multistorey building needs to have
    flights that go both up and down, whereas a ground floor landing needs only a
    flight that goes up, and this can consume less floor space. But automated
    fitting of flights in such a space is hard and Alexander has a pattern that
    says to allocate the entire vertical shaft for stairs, so we have assumed
    that, at least for now, stairs can only exist where cells are identical in
    all floors."

So the merged case is NOT a staircase by decision, not by oversight. Relaxing the
walk also disturbs three other things (`staircase_max`, the entrance corners fed
to `_stair_fit`, and `has_public_access_inside`, which is only set for a
circulation leaf that is NOT a stair) — measured in §39.72 at x0.0094 on one
artefact. What would reopen the question is a flight-fitter that can place a
mid-landing's up-and-down flights in a part-cell, not a different count.

Synthetic fixtures on purpose: corpus artefacts are regenerated by sweeps
(§39.27), so a test pinned to one can evaporate.
"""

from __future__ import annotations

import pytest

from homemaker_layout import dom, geometry, graph

PLOT = [[0.0, 0.0], [10.0, 0.0], [10.0, 8.0], [0.0, 8.0]]


def _two_storey(upper_left: str, upper_right: str | None, ground: str = "E"):
    """Ground floor `E | k1`; upstairs either the same split or ONE leaf.

    ``upper_right=None`` merges the upper storey into a single leaf covering both
    ground cells — the shape this test is about.
    """
    root = dom.Node(node=[list(p) for p in PLOT], height=3.0, elevation=0.0,
                    wall_inner=0.08, wall_outer=0.25, rotation=0,
                    division=[0.5, 0.5])
    root.left = dom.Node(type=ground)    # the stair cell
    root.right = dom.Node(type="k1")
    upper = dom.Node(rotation=0, height=3.0)
    if upper_right is None:
        upper.type = upper_left
    else:
        upper.division = [0.5, 0.5]
        upper.left = dom.Node(type=upper_left)
        upper.right = dom.Node(type=upper_right)
    root.above = upper
    dom.link(root)
    geometry.clear_cache()
    return root


def _stair_corners(root):
    lvls = dom.levels(root)
    fails: list[str] = []
    _base, circ = graph.build_graphs_with_circ(root, 1.2, fails.append,
                                               {"k1": "kitchen", "b1": "bedroom"})
    foot = lvls[0].leaves()[0]
    return foot, graph.stack_corners_in_use(foot, circ, lvls)


def test_a_column_of_identical_stair_cells_is_a_staircase():
    root = _two_storey("E", "b1")            # upstairs keeps the same split
    _leaf, corners = _stair_corners(root)
    assert corners, "an exact-path E column must be counted as a staircase"


def test_a_corridor_over_a_corridor_is_not_a_staircase():
    """§39.125, the reason for the label: a `C` cell repeated on the next floor
    is a corridor in the same place, which is what corridors do. The test above
    is this one's control -- the same tree with the other letter."""
    root = _two_storey("C", "b1", ground="C")
    _leaf, corners = _stair_corners(root)
    assert corners == []


def _three_storey(types: "tuple[str, str, str]"):
    """`<type> | k1` on each of three storeys, the left column typed as given."""
    root = _two_storey(types[1], "b1", ground=types[0])
    top = dom.Node(rotation=0, height=3.0, division=[0.5, 0.5])
    top.left = dom.Node(type=types[2])
    top.right = dom.Node(type="b2")
    root.above.above = top
    dom.link(root)
    geometry.clear_cache()
    return root


@pytest.mark.parametrize("column, is_stair", [
    (("E", "E", "E"), True),      # the full height
    (("E", "E", "O"), True),      # stops under a terrace: serves two floors
    (("E", "E", "C"), True),      # ...or under a corridor
    (("E", "O", "E"), False),     # reaches nothing: the cell above is not a stair
    (("C", "E", "E"), False),     # does not start at the ground
])
def test_a_shaft_may_stop_below_the_top_but_starts_at_the_ground(column, is_stair):
    _leaf, corners = _stair_corners(_three_storey(column))
    assert bool(corners) == is_stair


def test_a_stair_joins_the_storeys_it_serves(monkeypatch):
    """Two wings upstairs, each on its own stair, joined on the floor below:
    one building, and `level 1 not connected` must not fire (§39.125)."""
    def storey():
        n = dom.Node(rotation=0, height=3.0, division=[0.3, 0.3])
        n.left = dom.Node(type="E")
        n.right = dom.Node(rotation=0, division=[0.6, 0.6])
        n.right.right = dom.Node(type="E")
        return n
    root = storey()
    root.node = [list(p) for p in PLOT]
    root.elevation, root.wall_inner, root.wall_outer = 0.0, 0.08, 0.25
    root.right.left = dom.Node(type="C")          # the ground floor joins them
    root.above = storey()
    root.above.right.left = dom.Node(type="b1")   # upstairs a room stands between
    dom.link(root)
    geometry.clear_cache()
    _base, circ = graph.build_graphs_with_circ(root, 1.2, [].append, {"b1": "bedroom"})
    assert graph.circulation_joined(circ, 0)
    assert graph.circulation_joined(circ, 1)
    monkeypatch.setattr(graph, "STAIRS_JOIN_STOREYS", False)      # the control
    assert not graph.circulation_joined(circ, 1)


def test_a_merged_landing_over_the_stair_is_not_a_staircase():
    """The ruling: the shaft has to be the same cell all the way up.

    The upper storey here is ONE circulation leaf covering the stair AND the cell
    beside it — architecturally a landing over the stair, and deliberately not a
    staircase to this objective, because a part-cell cannot be shown to hold a
    mid-landing's flights and Alexander's pattern asks for the whole shaft.
    """
    root = _two_storey("E", None)            # upstairs merges both cells into one E
    leaf, corners = _stair_corners(root)

    # the merged state really does hold: what is above is a single circulation LEAF
    above = dom._above_more(leaf)
    assert above is not None and not above.divided and above.type == "E"
    # ... and it is still not a staircase
    assert corners == [], (
        "a merged cell over the stair must NOT count as a staircase -- owner's "
        "ruling, DESIGN.md §39.72; see this module's docstring before changing it")


def test_a_non_circulation_cell_above_is_not_a_staircase():
    root = _two_storey("b1", None)
    _leaf, corners = _stair_corners(root)
    assert corners == []


@pytest.mark.parametrize("upper", ["E", "C", "S"])
def test_the_rule_reads_the_type_exactly(upper):
    """Circulation over a stair does not continue it: the stack test is an
    exact match on the stair's own label, not on the circulation class that
    `E`, `C` and `S` all belong to."""
    root = _two_storey(upper, "b1")
    _leaf, corners = _stair_corners(root)
    assert bool(corners) == (upper == "E")


# --------------------------------------------------------------------------- #
# The operators' side of the ruling (DESIGN.md §39.74, homemaker-py-t7q).
#
# §39.73's census found seven live operators leave a building with no shaft at
# all, between 6% and 14% of draws. One of them is `support_outside`, which is a
# REPAIR operator and default ON: it was clearing `no outside space` and paying
# for it with `too few stairs` + `staircase volume` (x0.0225) in 8% of its draws.
# That is this operator's own stated doctrine broken -- "a repair that moves the
# fail to another level has repaired nothing" -- so it is guarded here rather
# than left for the A/B. The six exploratory operators are a different question
# (removing exploratory moves needs the measurement that needs a box).
# --------------------------------------------------------------------------- #

import numpy as np  # noqa: E402

from homemaker_layout import operators  # noqa: E402


def _shafted_with_a_stranded_terrace():
    """A 2-storey tree with an intact shaft, a stranded terrace and a bare storey.

    Ground: `C` shaft | `k1` | `O` garden. Upstairs: `C` over the shaft, `O` over
    the garden (stranded: it sits over outdoor space), `b1` over the kitchen. So
    level 1 has no USABLE outdoor space, which is what `support_outside` repairs,
    and the only enclosed cells it could take are the shaft and the bedroom.
    """
    root = dom.Node(node=[list(p) for p in PLOT], height=3.0, elevation=0.0,
                    wall_inner=0.08, wall_outer=0.25, rotation=0,
                    division=[0.34, 0.34])
    root.left = dom.Node(type="E")                       # the shaft
    root.right = dom.Node(rotation=0, division=[0.5, 0.5])
    root.right.left = dom.Node(type="k1")
    root.right.right = dom.Node(type="O")                # ground garden
    upper = dom.Node(rotation=0, height=3.0, division=[0.34, 0.34])
    upper.left = dom.Node(type="E")                      # shaft continues
    upper.right = dom.Node(rotation=0, division=[0.5, 0.5])
    upper.right.left = dom.Node(type="b1")
    upper.right.right = dom.Node(type="O")               # over the garden: stranded
    root.above = upper
    dom.link(root)
    geometry.clear_cache()
    return root


def test_support_outside_never_spends_the_staircase():
    root = _shafted_with_a_stranded_terrace()
    assert operators._shaft_paths(dom.levels(root)) == ["l"]
    for seed in range(24):
        child, desc = operators.mutate_support_outside(
            root, np.random.default_rng(seed), ["C", "O"])
        geometry.clear_cache()
        assert operators._shaft_paths(dom.levels(child)), (
            f"seed {seed} ({desc}) traded the staircase for outdoor space -- "
            "see this module's docstring")


def test_the_guard_is_what_prevents_it(monkeypatch):
    """Negative control: without the guard, some draw does break the shaft.

    Keeps the test above honest -- otherwise it could be passing because this
    fixture never offers the shaft as a candidate.
    """
    monkeypatch.setattr(operators, "_shaft_cells", lambda lvls: [])
    root = _shafted_with_a_stranded_terrace()
    broke = 0
    for seed in range(24):
        child, _desc = operators.mutate_support_outside(
            root, np.random.default_rng(seed), ["C", "O"])
        geometry.clear_cache()
        if not operators._shaft_paths(dom.levels(child)):
            broke += 1
    assert broke, "the fixture never offers the shaft, so the guard test is vacuous"


def test_repair_shaft_cuts_a_column_where_there_is_none():
    """`mutate_repair_shaft`: the move that gets a building its staircase back."""
    # ground `C | k1`, upstairs `O | b1`: no shaft (the cell over the stair is
    # outdoors), and the left column is generic on both storeys, so the repair
    # should cut a strip out of it rather than spend the kitchen or the bedroom
    root = _two_storey("O", "b1")
    assert not operators._shaft_paths(dom.levels(root))
    got = 0
    for seed in range(8):
        child, desc = operators.mutate_repair_shaft(
            root, np.random.default_rng(seed), ["C", "O"])
        geometry.clear_cache()
        if "noop" in desc:
            continue
        got += 1
        assert operators._shaft_paths(dom.levels(child)), desc
        # the cell it cut is still there, merely smaller: nothing was retyped away
        types = {lf.type for lvl in dom.levels(child) for lf in lvl.leaves()}
        assert "k1" in types, "the repair spent a required room"
    assert got, "the repair never fired where a generic column was available"


def test_repair_shaft_is_silent_where_a_shaft_is_intact():
    root = _two_storey("E", "b1")          # an exact E column: nothing to repair
    assert operators._shaft_paths(dom.levels(root))
    for seed in range(4):
        _child, desc = operators.mutate_repair_shaft(
            root, np.random.default_rng(seed), ["C", "O"])
        assert "noop" in desc, desc


def test_repair_shaft_opens_a_merged_upper_storey_first():
    """A merged storey is subdivided back into alignment, then cut.

    With the storey above undivided, no address below the root exists up there, so
    there is nothing to cut in alignment -- until the repair divides it back down
    to the address. It can do that without measuring anything: the storey below has
    the finer tree, and a node whose path is divided below INHERITS its cut
    (§39.70), so the division lands on the wall that is already there.
    """
    root = _two_storey("O", None)          # upstairs is one undivided leaf
    assert not operators._shaft_paths(dom.levels(root))
    fired = 0
    for seed in range(8):
        child, desc = operators.mutate_repair_shaft(
            root, np.random.default_rng(seed), ["C", "O"])
        geometry.clear_cache()
        if "noop" in desc:
            continue
        fired += 1
        assert "to align" in desc, desc
        assert operators._shaft_paths(dom.levels(child)), desc
        # the storey it opened keeps its outdoor space: the new siblings inherit
        # the merged cell's type, so nothing was retyped away
        upper = dom.levels(child)[1]
        assert any(lf.type == "O" for lf in upper.leaves()), desc
    assert fired, "the repair never opened the merged storey"


def test_repair_shaft_will_not_divide_a_room_to_reach_an_address():
    """Refusal 1: dividing a room clones its code and fails `too many spaces`.

    Ground `C | k1`; upstairs ONE `b1` covering both. Reaching either ground
    address upstairs would mean dividing the bedroom into two bedrooms, so there is
    no column and the operator says so instead of minting a duplicate.
    """
    root = _two_storey("b1", None)
    assert not operators._shaft_paths(dom.levels(root))
    for seed in range(6):
        child, desc = operators.mutate_repair_shaft(
            root, np.random.default_rng(seed), ["C", "O"])
        assert "noop" in desc, desc
        types = [lf.type for lvl in dom.levels(child) for lf in lvl.leaves()]
        assert types.count("b1") == 1, types


def test_repair_shaft_will_not_undivide_a_finer_storey_to_reach_an_address():
    """Refusal 2: the storey above has a FINER tree at the address.

    Ground `C | (k1 | O)`. Upstairs the left cell is split again into `O | b1`, so
    the address `l` EXISTS but is divided: getting a leaf there means undividing
    over whatever it holds, which is a different move. The two right-hand addresses
    are refused for the other reason -- reaching them upstairs would divide the
    bedroom covering them -- so there is no candidate at all and the operator says
    so.

    Note what is NOT refused, and why this fixture had to be built carefully: a
    column whose cells are ROOMS is fine, because cutting narrows a room instead of
    cloning it. Only reaching THROUGH a room by subdivision is refused.
    """
    root = dom.Node(node=[list(p) for p in PLOT], height=3.0, elevation=0.0,
                    wall_inner=0.08, wall_outer=0.25, rotation=0,
                    division=[0.4, 0.4])
    root.left = dom.Node(type="C")
    root.right = dom.Node(rotation=0, division=[0.5, 0.5])
    root.right.left = dom.Node(type="k1")
    root.right.right = dom.Node(type="O")
    upper = dom.Node(rotation=0, height=3.0, division=[0.4, 0.4])
    upper.left = dom.Node(rotation=0, division=[0.5, 0.5])
    upper.left.left = dom.Node(type="O")
    upper.left.right = dom.Node(type="b1")
    upper.right = dom.Node(type="b2")        # one room over both ground cells
    root.above = upper
    dom.link(root)
    geometry.clear_cache()
    assert not operators._shaft_paths(dom.levels(root))
    for seed in range(6):
        child, desc = operators.mutate_repair_shaft(
            root, np.random.default_rng(seed), ["C", "O"])
        assert "noop" in desc, desc
        types = [lf.type for lvl in dom.levels(child) for lf in lvl.leaves()]
        assert types.count("b2") == 1, types


# --------------------------------------------------------------------------- #
# `mutate_stair`: the move that writes the label (§39.125)
# --------------------------------------------------------------------------- #
def test_stair_makes_a_staircase_of_a_stacked_corridor():
    """What the old rule inferred, as a move: `C` over `C` becomes `E` over `E`."""
    root = _two_storey("C", "b1", ground="C")
    assert not operators._shaft_paths(dom.levels(root))
    child, desc = operators.mutate_stair(root, np.random.default_rng(0), ["C", "O"])
    assert desc.startswith("stair make"), desc
    assert operators._shaft_paths(dom.levels(child)) == ["l"]
    # ...and the parent is not touched
    assert not operators._shaft_paths(dom.levels(root))


def test_stair_never_unmakes_the_last_staircase():
    root = _two_storey("E", "b1")
    for seed in range(8):
        child, desc = operators.mutate_stair(root, np.random.default_rng(seed), ["C", "O"])
        assert "noop" in desc, desc
        assert operators._shaft_paths(dom.levels(child)) == ["l"]


def test_stair_unmakes_one_of_two_and_the_guard_is_what_keeps_the_last(monkeypatch):
    def storey():
        n = dom.Node(rotation=0, height=3.0, division=[0.3, 0.3])
        n.left = dom.Node(type="E")
        n.right = dom.Node(rotation=0, division=[0.6, 0.6])
        n.right.left = dom.Node(type="k1")
        n.right.right = dom.Node(type="E")
        return n
    root = storey()
    root.node = [list(p) for p in PLOT]
    root.elevation, root.wall_inner, root.wall_outer = 0.0, 0.08, 0.25
    root.above = storey()
    root.above.right.left.type = "b1"
    dom.link(root)
    geometry.clear_cache()
    assert len(operators._shaft_paths(dom.levels(root))) == 2
    child, desc = operators.mutate_stair(root, np.random.default_rng(0), ["C", "O"])
    assert desc.startswith("stair unmake"), desc
    assert len(operators._shaft_paths(dom.levels(child))) == 1
    # a second draw on the child may not take the one that is left
    again, desc = operators.mutate_stair(child, np.random.default_rng(1), ["C", "O"])
    assert len(operators._shaft_paths(dom.levels(again))) >= 1, desc
