"""A staircase needs the same cell on every storey — the owner's ruling, pinned.

`graph.stack_corners_in_use` walks `dom._above_node` (Urb's `Above`, the EXACT id
path), so a storey that MERGES the cell over the stair breaks the stack and the
building has no staircase. `homemaker-py-m4d` asked whether that is a defect,
since every other vertical predicate in `dom` walks the forgiving `_above_more`,
and since 31 of the corpus's 170 ground-floor circulation stacks are in exactly
that state against 29 the scorer accepts (DESIGN.md §39.72).

THE OWNER'S RULING (2026-09-27, DESIGN.md §39.72), which is why this test exists:

    "A first floor circulation cell that is split below into circulation and some
    other usage could in principle form a staircase, and this is a common pattern
    in real buildings, eg. a mid-landing in a multistorey building needs to have
    flights that go both up and down, whereas a ground floor landing needs only a
    flight that goes up, and this can consume less floor space. But automated
    fitting of flights in such a space is hard and Alexander has a pattern that
    says to allocate the entire vertical shaft for stairs, so we have assumed
    that, at least for now, stairs can only exist where cells are identical in
    all floors."

So the merged case is NOT a staircase by decision, not by oversight. Relaxing the
walk also disturbs three other things (`staircase_max`, the entrance corners fed
to `_stair_fit`, and `has_public_access_inside`, which is only set for a
circulation leaf that is NOT a stair) — measured in §39.72 at x0.0094 on one
artefact. What would reopen the question is a flight-fitter that can place a
mid-landing's up-and-down flights in a part-cell, not a different count.

Synthetic fixtures on purpose: corpus artefacts are regenerated by sweeps
(§39.27), so a test pinned to one can evaporate.
"""

from __future__ import annotations

import pytest

from homemaker_layout import dom, geometry, graph

PLOT = [[0.0, 0.0], [10.0, 0.0], [10.0, 8.0], [0.0, 8.0]]


def _two_storey(upper_left: str, upper_right: str | None):
    """Ground floor `C | k1`; upstairs either the same split or ONE leaf.

    ``upper_right=None`` merges the upper storey into a single leaf covering both
    ground cells — the shape this test is about.
    """
    root = dom.Node(node=[list(p) for p in PLOT], height=3.0, elevation=0.0,
                    wall_inner=0.08, wall_outer=0.25, rotation=0,
                    division=[0.5, 0.5])
    root.left = dom.Node(type="C")       # the stair cell
    root.right = dom.Node(type="k1")
    upper = dom.Node(rotation=0, height=3.0)
    if upper_right is None:
        upper.type = upper_left
    else:
        upper.division = [0.5, 0.5]
        upper.left = dom.Node(type=upper_left)
        upper.right = dom.Node(type=upper_right)
    root.above = upper
    dom.link(root)
    geometry.clear_cache()
    return root


def _stair_corners(root):
    lvls = dom.levels(root)
    fails: list[str] = []
    _base, circ = graph.build_graphs_with_circ(root, 1.2, fails.append,
                                               {"k1": "kitchen", "b1": "bedroom"})
    ground_c = next(lf for lf in lvls[0].leaves() if lf.type == "C")
    return ground_c, graph.stack_corners_in_use(ground_c, circ, lvls)


def test_a_column_of_identical_circulation_cells_is_a_staircase():
    root = _two_storey("C", "b1")            # upstairs keeps the same split
    _leaf, corners = _stair_corners(root)
    assert corners, "an exact-path C column must be counted as a staircase"


def test_a_merged_landing_over_the_stair_is_not_a_staircase():
    """The ruling: the shaft has to be the same cell all the way up.

    The upper storey here is ONE circulation leaf covering the stair AND the cell
    beside it — architecturally a landing over the stair, and deliberately not a
    staircase to this objective, because a part-cell cannot be shown to hold a
    mid-landing's flights and Alexander's pattern asks for the whole shaft.
    """
    root = _two_storey("C", None)            # upstairs merges both cells into one C
    leaf, corners = _stair_corners(root)

    # the merged state really does hold: what is above is a single circulation LEAF
    above = dom._above_more(leaf)
    assert above is not None and not above.divided and above.type == "C"
    # ... and it is still not a staircase
    assert corners == [], (
        "a merged cell over the stair must NOT count as a staircase -- owner's "
        "ruling, DESIGN.md §39.72; see this module's docstring before changing it")


def test_a_non_circulation_cell_above_is_not_a_staircase():
    root = _two_storey("b1", None)
    _leaf, corners = _stair_corners(root)
    assert corners == []


@pytest.mark.parametrize("upper", ["C", "S"])
def test_the_rule_reads_the_type_exactly(upper):
    """`S` (sahn) is not `C`: the stack test is an exact type match, not a class.

    Not a separate decision — `preprocess_building` converts `S` to `O` before
    scoring unless `allow_sahn_circulation` is set (§39.66) — but the stack walk
    itself is exact, and this records which it is.
    """
    root = _two_storey(upper, "b1")
    _leaf, corners = _stair_corners(root)
    assert bool(corners) == (upper == "C")


# --------------------------------------------------------------------------- #
# The operators' side of the ruling (DESIGN.md §39.74, homemaker-py-t7q).
#
# §39.73's census found seven live operators leave a building with no shaft at
# all, between 6% and 14% of draws. One of them is `support_outside`, which is a
# REPAIR operator and default ON: it was clearing `no outside space` and paying
# for it with `too few stairs` + `staircase volume` (x0.0225) in 8% of its draws.
# That is this operator's own stated doctrine broken -- "a repair that moves the
# fail to another level has repaired nothing" -- so it is guarded here rather
# than left for the A/B. The six exploratory operators are a different question
# (removing exploratory moves needs the measurement that needs a box).
# --------------------------------------------------------------------------- #

import numpy as np  # noqa: E402

from homemaker_layout import operators  # noqa: E402


def _shafted_with_a_stranded_terrace():
    """A 2-storey tree with an intact shaft, a stranded terrace and a bare storey.

    Ground: `C` shaft | `k1` | `O` garden. Upstairs: `C` over the shaft, `O` over
    the garden (stranded: it sits over outdoor space), `b1` over the kitchen. So
    level 1 has no USABLE outdoor space, which is what `support_outside` repairs,
    and the only enclosed cells it could take are the shaft and the bedroom.
    """
    root = dom.Node(node=[list(p) for p in PLOT], height=3.0, elevation=0.0,
                    wall_inner=0.08, wall_outer=0.25, rotation=0,
                    division=[0.34, 0.34])
    root.left = dom.Node(type="C")                       # the shaft
    root.right = dom.Node(rotation=0, division=[0.5, 0.5])
    root.right.left = dom.Node(type="k1")
    root.right.right = dom.Node(type="O")                # ground garden
    upper = dom.Node(rotation=0, height=3.0, division=[0.34, 0.34])
    upper.left = dom.Node(type="C")                      # shaft continues
    upper.right = dom.Node(rotation=0, division=[0.5, 0.5])
    upper.right.left = dom.Node(type="b1")
    upper.right.right = dom.Node(type="O")               # over the garden: stranded
    root.above = upper
    dom.link(root)
    geometry.clear_cache()
    return root


def test_support_outside_never_spends_the_staircase():
    root = _shafted_with_a_stranded_terrace()
    assert operators._shaft_paths(dom.levels(root)) == ["l"]
    for seed in range(24):
        child, desc = operators.mutate_support_outside(
            root, np.random.default_rng(seed), ["C", "O"])
        geometry.clear_cache()
        assert operators._shaft_paths(dom.levels(child)), (
            f"seed {seed} ({desc}) traded the staircase for outdoor space -- "
            "see this module's docstring")


def test_the_guard_is_what_prevents_it(monkeypatch):
    """Negative control: without the guard, some draw does break the shaft.

    Keeps the test above honest -- otherwise it could be passing because this
    fixture never offers the shaft as a candidate.
    """
    monkeypatch.setattr(operators, "_shaft_cells", lambda lvls: [])
    root = _shafted_with_a_stranded_terrace()
    broke = 0
    for seed in range(24):
        child, _desc = operators.mutate_support_outside(
            root, np.random.default_rng(seed), ["C", "O"])
        geometry.clear_cache()
        if not operators._shaft_paths(dom.levels(child)):
            broke += 1
    assert broke, "the fixture never offers the shaft, so the guard test is vacuous"


def test_repair_shaft_cuts_a_column_where_there_is_none():
    """`mutate_repair_shaft`: the move that gets a building its staircase back."""
    # ground `C | k1`, upstairs `O | b1`: no shaft (the cell over the stair is
    # outdoors), and the left column is generic on both storeys, so the repair
    # should cut a strip out of it rather than spend the kitchen or the bedroom
    root = _two_storey("O", "b1")
    assert not operators._shaft_paths(dom.levels(root))
    got = 0
    for seed in range(8):
        child, desc = operators.mutate_repair_shaft(
            root, np.random.default_rng(seed), ["C", "O"])
        geometry.clear_cache()
        if "noop" in desc:
            continue
        got += 1
        assert operators._shaft_paths(dom.levels(child)), desc
        # the cell it cut is still there, merely smaller: nothing was retyped away
        types = {lf.type for lvl in dom.levels(child) for lf in lvl.leaves()}
        assert "k1" in types, "the repair spent a required room"
    assert got, "the repair never fired where a generic column was available"


def test_repair_shaft_is_silent_where_a_shaft_is_intact():
    root = _two_storey("C", "b1")          # an exact C column: nothing to repair
    assert operators._shaft_paths(dom.levels(root))
    for seed in range(4):
        _child, desc = operators.mutate_repair_shaft(
            root, np.random.default_rng(seed), ["C", "O"])
        assert "noop" in desc, desc


def test_repair_shaft_declines_when_no_address_exists_on_every_storey():
    """The known limit, recorded: a merged upper storey offers no column.

    With the storey above undivided, no address below the root exists up there, so
    there is nothing to cut in alignment. Getting a shaft into THAT shape has to
    subdivide the upper storey first, which is a compound move and a different
    bead; declining is the honest answer rather than a half-repair (§39.53).
    """
    root = _two_storey("O", None)          # upstairs is one undivided leaf
    assert not operators._shaft_paths(dom.levels(root))
    for seed in range(4):
        _child, desc = operators.mutate_repair_shaft(
            root, np.random.default_rng(seed), ["C", "O"])
        assert "noop" in desc and "column" in desc, desc
