"""Generic leaves flex down to their DECLARED width, not to a number in the solver.

`solver.solve_ratios` lets circulation and outside leaves absorb whatever area the
rooms do not claim, with a one-sided penalty to stop them collapsing into slivers.
Until §39.76 that penalty was one hard-coded `min_width_generic=1.2` for every
generic leaf, while the objective reads `width_circulation` [2.4, 0.2] and
`width_outside` (then [3.0, 0.3]) from the same config the room targets come from --
so the floor sat BELOW both, at 1.2 m against fail thresholds of 1.971 m and
2.356 m, and the solved point routinely failed `quality_width` on exactly the
leaves the term exists to protect (41 width fails over the twelve corpus
topologies, 11 once the declaration is read -- `homemaker-py-r8c`).

What is pinned here is the reading of the declaration, not the measured margin:
the numbers move with the config, the direction does not.

Synthetic fixtures on purpose: corpus artefacts are regenerated by sweeps
(§39.27), so a test pinned to one can evaporate.
"""

from __future__ import annotations

import math

from homemaker_layout import dom, geometry, solver
from homemaker_layout.fitness import CONF_DEFAULTS
from homemaker_layout.programme import SpaceReq

# A plot too small for its programme, so the corridor is what gets squeezed.
PLOT = [[0.0, 0.0], [8.0, 0.0], [8.0, 4.0], [0.0, 4.0]]

# Read from the defaults, not copied: §39.87 moved `width_outside` to [2.3, 0.05]
# and three tests here failed only because they held their own copy of [3.0, 0.3].
WIDTH_CIRCULATION = tuple(CONF_DEFAULTS["width_circulation"])
WIDTH_OUTSIDE = tuple(CONF_DEFAULTS["width_outside"])


def _fail_threshold(params: tuple[float, float]) -> float:
    """Width below which `_clipped_gaussian(w, t, s, "above")` drops under 0.1."""
    target, sigma = params
    return target - sigma * math.sqrt(2 * math.log(10))


def _corridor_and_room(left_type: str = "C"):
    """One cut: a generic leaf beside a living room that wants nearly the plot."""
    root = dom.Node(node=[list(p) for p in PLOT], height=3.0, elevation=0.0,
                    wall_inner=0.08, wall_outer=0.25, rotation=0,
                    division=[0.5, 0.5])
    root.left = dom.Node(type=left_type)
    root.right = dom.Node(type="l1")
    dom.link(root)
    geometry.clear_cache()
    return root


TARGETS = {"l1": SpaceReq(code="l1", name="living", size=28.0, size_sigma=3.5,
                          width=3.0, proportion=1.5)}


def _solve(root, **kw):
    solver.solve_ratios(root, TARGETS, **kw)
    geometry.clear_cache()
    return geometry.length_narrowest(root.left)


# --------------------------------------------------------------------------- #
# the declaration is read
# --------------------------------------------------------------------------- #
def test_a_corridor_is_held_above_its_declared_fail_threshold():
    """The headline: the default clears `quality_width`, the old knob does not."""
    declared = _solve(_corridor_and_room())
    knob = _solve(_corridor_and_room(), min_width_generic=1.2)

    assert declared > _fail_threshold(WIDTH_CIRCULATION), (
        f"corridor solved to {declared:.3f} m, under width_circulation's "
        f"{_fail_threshold(WIDTH_CIRCULATION):.3f} m fail threshold")
    assert knob < _fail_threshold(WIDTH_CIRCULATION), (
        "the pre-§39.76 behaviour is the thing being fixed; if this passes, the "
        "fixture no longer squeezes the corridor and the test above proves less")
    assert declared > knob


def test_min_width_generic_restores_one_floor_for_every_generic_leaf():
    """The escape hatch: a float means the old uniform behaviour, whatever the
    class, which is how `diag_r8c_warmstart.py` reproduces the arms it measures."""
    narrow = _solve(_corridor_and_room(), min_width_generic=1.2)
    wide = _solve(_corridor_and_room(), min_width_generic=3.5)
    assert narrow < wide
    # the low floor lands on it; the high one pulls the corridor well past the
    # declared 2.4 before the room's own area residual stops it short of 3.5,
    # which is the point -- the override is what is being obeyed, not a target
    assert abs(narrow - 1.2) < 0.15
    assert wide > WIDTH_CIRCULATION[0] + 0.4


def test_min_width_generic_zero_drops_the_term():
    """0.0 is not 'no override' -- it removes the residual, and the room takes
    the area. `None` is what means 'use the declaration'."""
    off = _solve(_corridor_and_room(), min_width_generic=0.0)
    assert off < _solve(_corridor_and_room(), min_width_generic=1.2)


def test_a_conf_override_moves_the_floor():
    """The config is read per solve, not baked in: an architect who widens
    `width_circulation` widens the corridor the solver leaves."""
    default = _solve(_corridor_and_room())
    wider = _solve(_corridor_and_room(), conf={"width_circulation": [3.5, 0.2]})
    assert wider > default + 0.5


# --------------------------------------------------------------------------- #
# which leaves the rule applies to, and with which class's parameters
# --------------------------------------------------------------------------- #
def _two_storey_terrace():
    """Ground `O | k1`; above, `O` over each -- one unsupported, one supported."""
    root = dom.Node(node=[list(p) for p in PLOT], height=3.0, elevation=0.0,
                    wall_inner=0.08, wall_outer=0.25, rotation=0,
                    division=[0.5, 0.5])
    root.left = dom.Node(type="O")
    root.right = dom.Node(type="k1")
    upper = dom.Node(rotation=0, height=3.0, division=[0.5, 0.5])
    upper.left = dom.Node(type="O")      # over the ground terrace: a roof garden
    upper.right = dom.Node(type="O")     # over the kitchen: a supported terrace
    root.above = upper
    dom.link(root)
    geometry.clear_cache()
    return root


def test_a_roof_garden_is_exempt_and_a_supported_terrace_is_not():
    """`quality_width`'s own first branch: an outside leaf that is uncovered,
    unsupported and above ground scores 1.0 whatever its width, so pinning it
    wide would spend degrees of freedom the rooms want."""
    root = _two_storey_terrace()
    upper = root.above
    assert not dom.is_covered(upper.left) and not dom.is_supported(upper.left)
    assert dom.is_supported(upper.right)

    assert solver._generic_min_width(upper.left, None) is None
    assert solver._generic_min_width(upper.right, None) == WIDTH_OUTSIDE[0]


def test_a_ground_floor_outside_leaf_is_never_exempt():
    """The exemption is for what is above ground; a garden on the plot is not."""
    root = _two_storey_terrace()
    assert solver._generic_min_width(root.left, None) == WIDTH_OUTSIDE[0]


def test_sahn_takes_the_outside_width_not_circulation():
    """`S` is in both generic sets and takes the OUTSIDE parameter families,
    exactly as `get_space_params` and `fitness._generic_class` dispatch it
    (§39.4). Spelling decides nothing else."""
    root = _corridor_and_room("S")
    assert solver._generic_min_width(root.left, None) == WIDTH_OUTSIDE[0]

    circ = _corridor_and_room("C")
    assert solver._generic_min_width(circ.left, None) == WIDTH_CIRCULATION[0]


def test_a_programme_room_has_no_generic_width():
    """Rooms are driven by their own declared targets, not by this term."""
    root = _corridor_and_room()
    assert solver._generic_min_width(root.right, None) is None
