"""A staircase needs the same cell on every storey — the owner's ruling, pinned.

`graph.stack_corners_in_use` walks `dom._above_node` (Urb's `Above`, the EXACT id
path), so a storey that MERGES the cell over the stair breaks the stack and the
building has no staircase. `homemaker-py-m4d` asked whether that is a defect,
since every other vertical predicate in `dom` walks the forgiving `_above_more`,
and since 31 of the corpus's 170 ground-floor circulation stacks are in exactly
that state against 29 the scorer accepts (DESIGN.md §39.72).

THE OWNER'S RULING (2026-09-27, DESIGN.md §39.72), which is why this test exists:

    "A first floor circulation cell that is split below into circulation and some
    other usage could in principle form a staircase, and this is a common pattern
    in real buildings, eg. a mid-landing in a multistorey building needs to have
    flights that go both up and down, whereas a ground floor landing needs only a
    flight that goes up, and this can consume less floor space. But automated
    fitting of flights in such a space is hard and Alexander has a pattern that
    says to allocate the entire vertical shaft for stairs, so we have assumed
    that, at least for now, stairs can only exist where cells are identical in
    all floors."

So the merged case is NOT a staircase by decision, not by oversight. Relaxing the
walk also disturbs three other things (`staircase_max`, the entrance corners fed
to `_stair_fit`, and `has_public_access_inside`, which is only set for a
circulation leaf that is NOT a stair) — measured in §39.72 at x0.0094 on one
artefact. What would reopen the question is a flight-fitter that can place a
mid-landing's up-and-down flights in a part-cell, not a different count.

Synthetic fixtures on purpose: corpus artefacts are regenerated by sweeps
(§39.27), so a test pinned to one can evaporate.
"""

from __future__ import annotations

import pytest

from homemaker_layout import dom, geometry, graph

PLOT = [[0.0, 0.0], [10.0, 0.0], [10.0, 8.0], [0.0, 8.0]]


def _two_storey(upper_left: str, upper_right: str | None):
    """Ground floor `C | k1`; upstairs either the same split or ONE leaf.

    ``upper_right=None`` merges the upper storey into a single leaf covering both
    ground cells — the shape this test is about.
    """
    root = dom.Node(node=[list(p) for p in PLOT], height=3.0, elevation=0.0,
                    wall_inner=0.08, wall_outer=0.25, rotation=0,
                    division=[0.5, 0.5])
    root.left = dom.Node(type="C")       # the stair cell
    root.right = dom.Node(type="k1")
    upper = dom.Node(rotation=0, height=3.0)
    if upper_right is None:
        upper.type = upper_left
    else:
        upper.division = [0.5, 0.5]
        upper.left = dom.Node(type=upper_left)
        upper.right = dom.Node(type=upper_right)
    root.above = upper
    dom.link(root)
    geometry.clear_cache()
    return root


def _stair_corners(root):
    lvls = dom.levels(root)
    fails: list[str] = []
    _base, circ = graph.build_graphs_with_circ(root, 1.2, fails.append,
                                               {"k1": "kitchen", "b1": "bedroom"})
    ground_c = next(lf for lf in lvls[0].leaves() if lf.type == "C")
    return ground_c, graph.stack_corners_in_use(ground_c, circ, lvls)


def test_a_column_of_identical_circulation_cells_is_a_staircase():
    root = _two_storey("C", "b1")            # upstairs keeps the same split
    _leaf, corners = _stair_corners(root)
    assert corners, "an exact-path C column must be counted as a staircase"


def test_a_merged_landing_over_the_stair_is_not_a_staircase():
    """The ruling: the shaft has to be the same cell all the way up.

    The upper storey here is ONE circulation leaf covering the stair AND the cell
    beside it — architecturally a landing over the stair, and deliberately not a
    staircase to this objective, because a part-cell cannot be shown to hold a
    mid-landing's flights and Alexander's pattern asks for the whole shaft.
    """
    root = _two_storey("C", None)            # upstairs merges both cells into one C
    leaf, corners = _stair_corners(root)

    # the merged state really does hold: what is above is a single circulation LEAF
    above = dom._above_more(leaf)
    assert above is not None and not above.divided and above.type == "C"
    # ... and it is still not a staircase
    assert corners == [], (
        "a merged cell over the stair must NOT count as a staircase -- owner's "
        "ruling, DESIGN.md §39.72; see this module's docstring before changing it")


def test_a_non_circulation_cell_above_is_not_a_staircase():
    root = _two_storey("b1", None)
    _leaf, corners = _stair_corners(root)
    assert corners == []


@pytest.mark.parametrize("upper", ["C", "S"])
def test_the_rule_reads_the_type_exactly(upper):
    """`S` (sahn) is not `C`: the stack test is an exact type match, not a class.

    Not a separate decision — `preprocess_building` converts `S` to `O` before
    scoring unless `allow_sahn_circulation` is set (§39.66) — but the stack walk
    itself is exact, and this records which it is.
    """
    root = _two_storey(upper, "b1")
    _leaf, corners = _stair_corners(root)
    assert bool(corners) == (upper == "C")
